#!/bin/sh

#!/bin/sh
#
# Copyright 2014, Reinhard Tartler <siretart@debian.org>
#
# These helper script is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This script is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#

set -ex

for package in `cat packages.txt`; do
    if [ ! -d $package ]; then
        echo "Rebuilding $package"
        ./git_experimental_source $package
        ./$package/build.sh || true
    else
        echo "Skipping $package"
    fi
done
